language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bb-leaflet' ]; then cd .. && eval "mv $currentfolder generator-bb-leaflet" && cd generator-bb-leaflet; fi

